### PR TITLE
Added features: add_album, add_song, play_song

### PR DESCRIPTION
**Pull request by crackulator**
Do you want these features I added? Playing individual songs, and adding songs and albums to the existing playlist...

(This is my first attempt at GitHubbing, so let me know if I'm not doing it right...)

### CODE REVIEW

**Comment by Arn-O** [comment]
Great! Thank for improving PyKodi.

**Comment by Arn-O** [comment]
Hi.

A major refactoring of PyKodi will be released in the next days.
"pykodi.py" will now be a standalone module that could be used by any
Python projects around Kodi. A cmd client will also be provided.

The modification that you have provided will still be part of it, with a
renaming. The function will be named playlist_add_songs,
playlist_add_albums, play_songs and play_albums.

If you are still using PyKodi, maybe you could test the next release that
it is currently stored on the refactor branch. The code is subject to
modification is not yet considered as stable.

All the best!

Ar.

**Comment by crackulator** [comment]
Cool, thanks... I'll try it when I have a chance.

(I'm aspiring one day to make a curses-style music player based on your work, sounds like your refactoring will be a very useful step, I'll be able to use your module instead of just aping the relevant bits. Nice work!)

tx, crackulator

**Comment by Arn-O** [comment]
Hi.

That's precisely the idea. You will just have to ``import pykodi`` and you will be able to call the function directly. Processing functions are separated from the display functions, so that will be really easy to create a new client and focusing on the UI only.

I will create a simple iPython notebook to illustrate that.

All the best.

**Pull request merged**
